import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";
import { Navbar } from "./components/navbar";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Mandarin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} font-sans bg-background text-foreground`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
